import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import GlobalNavigator from '@/components/layout/global-navigator';
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/auth';
import ThemeProvider from '@/components/shared/theme-provider';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider session={session}>
            <GlobalNavigator />
            {children}
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
